apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pjmhla9z5-go 
  janus-idp.io/tekton: pjmhla9z5-go
  backstage.io/kubernetes-id: pjmhla9z5-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pjmhla9z5-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml