apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pjmhla9z5-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pjmhla9z5-go 
  name: pjmhla9z5-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pjmhla9z5-go 
